### ISSUE TITLE
Can't get it work. It breaks the WP-API Plugin calls too

### ISSUE THREAD

**Issue by harikrishnanvh** [modemlooper/BP-API#15]
BP-API Main and Develop branches on activation breaking the WP-API Calls also (Eg: wp-json/posts) giving an error 500 Internal server error

**Comment by modemlooper** [comment]
u have to use the develop branch of api on github

**Comment by harikrishnanvh** [comment]
Thanks a ton. It worked. Great work and amazing plugin. Is there any future plans to have a proper documentation. Thanks again for sharing

**Comment by modemlooper** [comment]
yup, put dev on hold a bit as the WP-API is getting a rewrite. once its more stable will pick up again

**Comment by modemlooper** [comment]
yup, put dev on hold a bit as the WP-API is getting a rewrite. once its more stable will pick up again

**Comment by paulgibbs** [comment]
@modemlooper is this still true? I had heard recently that WP API was good to use now for custom endpoints (but not for things building on WP core endpoints).

**Comment by modemlooper** [comment]
2.0 develop branch still being worked on

**Comment by mottolini** [comment]
I just adapted this plugin to use the V1.2 WP-API master branch. Would like to share my work so that anybody else could contribute and create a stable BP-API interface to Buddypress

**Comment by modemlooper** [comment]
Thanks, but the goal is to release when WP-API is in core and that code will be the develop branch
