### ISSUE TITLE
404 no route

### ISSUE THREAD

**Issue by pirony** [modemlooper/BP-API#17]
Hi there,
wanted to give a try at this plugin, but can't get it to work.
I'm using the develop branch of the WP API (v2) but I still get a 404 error when visiting
<code>.../wp-json/bp/activity</code> or <code>.../wp-json/wp/v2/bp/activity</code>

Any idea? Thanks

**Comment by modemlooper** [comment]
download bp-api again, the wp-api had some method/class name changes from json to rest
