### ISSUE TITLE
WPRest Api v1 compatibility 

### ISSUE THREAD

**Issue by hefejeff** [modemlooper/BP-API#21]
Any chance you have an old version of this which was built for Version 1.  I want to use this but believe that I should be using version 1 until version 2 is stable.

**Comment by modemlooper** [comment]
Version 2 is stable, there is a plugin https://wordpress.org/plugins/rest-api/

**Comment by hefejeff** [comment]
Excellent News.  I wonder if the guys at Pods have a version of their api for version 2. If so I will start migrating over right away. I have already asked through slack and am awaiting a response.  Thanks again.
