### ISSUE TITLE
Xprofile CRUD actions?

### ISSUE THREAD

**Issue by beatelite** [modemlooper/BP-API#22]
Hey, love the project so far. Do you have any plans to allow us to perform any CRUD actions on xprofile fields?

didn't see anything in docs

**Comment by modemlooper** [comment]
yup, going to be some updates soon

**Comment by modemlooper** [comment]
yup, going to be some updates soon

**Comment by beatelite** [comment]
Awesome. one more q: Will there be a better way to access the "action" key within the activity object? 

For example, the current result looks like this: 

"activity": [
    {
 "action": "<a href=\"http://site.dev/members/m4/\" title=\"beatelite\">Beatelite</a> posted an update <a href=\"http://sitel.dev/activity/p/73/\" class=\"view activity-time-since\" title=\"View Discussion\"><span class=\"time-since\">1 month ago</span></a>"
}
]
That's a lot of data in a string. 

Or, do you have any recommended ways to work with it? 

I'm using angular and am fairly new to it but I'd be open to whatever you found works.

**Comment by beatelite** [comment]
ok, saw the update to the x-profile end point in the dev branch. If you feel it's ready, I can start testing it out.

Moving my last comment to a new thread since it's a separate question.
